### ISSUE TITLE
Custom Checks do not work with SendOnly buses

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceControl.Plugins.v5#5]
If the bus is a send-only bus custom checks are not initialized. Looking at the code the underlying issue is that the feature relies on the IWantToRunWhenBusStartAndStop that is not invoked for send-only buses.

**Comment by JoeShook** [comment]
Any decision on this?

**Comment by danielmarbach** [comment]
Let me chime in on this one. At the moment we cannot properly fix that issue. The TimerBasedPeriodicCheck is disposable because it uses internally a timer which needs to be disposed in order to not fire the callbacks anymore. This requires the PeriodicCheckMonitor to be IDisposable. Unfortunately the core doesn't support disposing the created startup components. Relying only on the container is not an option because we support containers that don't track disposables or transient instances.

cc @Particular/engineers what do you think we should solve this? My opinion is that we need to change the core to start and stop also in SendOnly scenarios.

**Comment by johnsimons** [comment]
+1

**Comment by indualagarsamy** [comment]
@JoeShook: Currently this feature is not supported. At the moment, send only endpoints are light weight endpoints that don't have a queue associated with it, that are used to just send messages. However, we will look into this and see what the implications are before we consider implementing this. 
At the moment, can you move the checks to a regular endpoint?  
@mauroservienti: Can you please raise an issue in the requirements to trigger a discussion?

**Comment by JoeShook** [comment]
I only have a sendonly endpoint on this machine.  I have two choices.  
1. Change this to a sendonly endpoint to a regular endpoint.  So then I end up with queues when I don't want them.  Just confuses things a bit.
2.  Put this check in a regular endpoint.  Because I am monitoring Windows File folders I have to manage service identities more, permissions to unc paths. etc....  

I think the custom check should be with the endpoint that is dependent on the checks.  With that in mind options 1 is my way to go.
